[package]
name = "fireup"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.98"
firecracker-vm = { path = "../firecracker-vm" }
firecracker-prepare = { path = "../firecracker-prepare" }
firecracker-process = { path = "../firecracker-process" }
clap = "4.5.41"
owo-colors = "4.2.2"
