[package]
name = "firecracker-vm"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.98"
glob = "0.3.2"
libc = "0.2.174"
num_cpus = "1.17.0"
owo-colors = "4.2.2"
serde_json = "1.0.141"
