[package]
name = "firecracker-process"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.98"
libc = "0.2.174"
owo-colors = "4.2.2"
