name: release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          sudo apt-get install libssl-dev pkg-config
          wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
      - uses: fluentci-io/setup-fluentci@v5
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build
        run: fluentci run . build
        env:
          TAG: ${{ env.RELEASE_VERSION }}
          TARGET: ${{ matrix.target }}
      - name: Upload release assets
        run: |
          for ext in tar.gz tar.gz.sha256; do
            export FILE=/assets/fireup_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.$ext
            fluentci run github_pipeline release_upload
          done
        env:
          TAG: ${{ env.RELEASE_VERSION }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
